//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAR_BD2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAR
    {
        public int ID_CARNAME { get; set; }
        public string NAME_CAR { get; set; }
        public string MODEL_CAR { get; set; }
        public string COLOR_CAR { get; set; }
        public string NUMBER_CAR { get; set; }
    }
}
