//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAR_BD2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUPPLIER
    {
        public int ID_SUPPLIER { get; set; }
        public string SURNAME { get; set; }
        public string SUPPLIER_NAME { get; set; }
        public string PATRONYMIC { get; set; }
    }
}
