//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAR_BD2
{
    using System;
    using System.Collections.Generic;
    
    public partial class WHERE_THE_CAR_COMES_FROM
    {
        public int ID_WHERE_THE_CAR_COMES_FROM { get; set; }
        public string TITLE { get; set; }
    }
}
